# Generated by Django 5.2.4 on 2025-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('email_required', 'Email required')], default='email_required', max_length=20),
        ),
    ]
