# Generated by Django 5.2.4 on 2025-08-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_options_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
